### PR TITLE
[BUGFIX] Fix breaking display of the toggle button in page preview

### PR DESCRIPTION
**Pull request by Apen**
Fix the toggle button in the TYPO3 preview (avoid line return)

### CODE REVIEW

**Review by fnagel — APPROVED** [review]
+1 by reading and testing with current development branch

**Comment by fnagel** [comment]
@Apen Would you mind rebasing this PR against latest development branch?

**Comment by fnagel** [comment]
@NamelessCoder Can we merge this? Helps a lot with the UI for Grid elements!

Before:
grafik

After: 
grafik

**Comment by Apen** [comment]
Must be good @fnagel

**Comment by NamelessCoder** [comment]
Thanks @Apen :)

**Pull request merged**
