### PR TITLE
[BUGFIX] Adapt to FlexForm language handling deprecation

### PR DESCRIPTION
**Pull request by mneuhaus**

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Solution confirmed in https://github.com/FluidTYPO3/flux/issues/1216

**Comment by achim71** [comment]
I'm still getting an empty array for pi_flexform. Had to change readDataArrayFromProvidersOrUsingDefaultMethod in Classes\ViewHelpers\Form\DataViewHelper.php
into
```
protected static function readDataArrayFromProvidersOrUsingDefaultMethod(array $providers, $record, $field)
    {
        if (0 === count($providers)) {
            $lang = static::getCurrentLanguageName();
            $pointer = static::getCurrentValuePointerName();
            
                $dataArray = static::$configurationService->convertFlexFormContentToArray(
                $record[$field],
                null,
                'lDEF',
                'vDEF'
            );
            
        } else {
            $dataArray = [];
            /** @var ProviderInterface $provider */
            foreach ($providers as $provider) {
                $data = (array) $provider->getFlexFormValues($record);
                $dataArray = RecursiveArrayUtility::merge($dataArray, $data);
            }
        }
        
        return $dataArray;
    }
```

**Comment by hputzek** [comment]
I had the same Issue as mentioned by achim71.

I use TYPO3 8.7 + flux 8.2.1

His fix did work for me.

**Comment by typo3ua** [comment]
**I use:**
TYPO3 8.7.10
FLUX 8.2.1
```
<flux:form.data table="tt_content" field="pi_flexform" uid="1" as="flexformData">
               {flexformData -> f:debug()}
</flux:form.data>
```
array(empty)

**Pull request merged**
