### PR TITLE
[BUGFIX] Fixing error issue when editing page properties

### PR DESCRIPTION
**Pull request by zoranilic**
According to RenderType description:
https://docs.typo3.org/typo3cms/TCAReference/ColumnsConfig/Type/Group.html#rendertype-default

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Thanks for the patch @zoranilic - just for the record, it appears you're not responsible for the unit tests failing on dev-master. I'll have to fix those and re-run the tests. Change itself looks good :)

**Comment by zoranilic** [comment]
One more place for renderingType to be set to NULL. It's "Fal" object.

**Comment by NamelessCoder** [comment]
Oops! I forgot we had this pull request open - so I went and pushed a change to nullify renderType on the File component. Sorry to remove that from your patch but in order to resolve the conflict it had to be done.

**Comment by NamelessCoder** [comment]
Thank you for the patch - and welcome to the list of contributors! :tada

**Comment by zoranilic** [comment]
My pleasure. ;)

**Pull request merged**
