### PR TITLE
[FEATURE] Add functional tests

### PR DESCRIPTION
**Pull request by galoppi**

### CODE REVIEW

**Comment by cedricziel** [comment]
Hi there - Thank you for your contribution!

Please amend the the message of the second commit to have the first word uppercase. Otherwise Travis would decline it in the CGL - checker.

**Comment by NamelessCoder** [comment]
Don't merge - I will take care of this one manually. It has relations to our `fluidtypo3-development` package and the manipulation of the composer class loader should instead be depended upon in the unit test bootstrapper.

**Comment by galoppi** [comment]
Yes, I understand.
I think we need another test script in fluidtypo3-development for the functional tests as we need a fully functional typo3 environment and a database with read/write access.
And maybe another approach for the autoloading.
To run the tests we need a script like this:
`typo3DatabaseName="dbname" typo3DatabaseUsername="dbuser" typo3DatabasePassword="dbpass" typo3DatabaseHost="dbhost" TYPO3_PATH_WEB="path/to/docroot" ./vendor/bin/phpunit -v --strict -c phpunit-functionaltests.xml.dist --process-isolation --bootstrap vendor/typo3/cms/typo3/sysext/core/Build/FunctionalTestsBootstrap.php Tests/Functional/Service/ContentServiceTest.php`

**Comment by NamelessCoder** [comment]
Please leave open for now - I'll use this and the comments (thanks!) to create functional test runners in fluidtypo3-development. It will be nice to be able to re-run this PR test for that. I may ask for a rebase at some point ;)

**Pull request closed without merging**
