### PR TITLE
[FEATURE] show item footer

### PR DESCRIPTION
**Pull request by netzloesungen**
follow-up of https://github.com/FluidTYPO3/flux/pull/699

Added feature shows the footer information of an item in the backend as done by the drawItem function.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
#### This is an automated comment based on an automated formal commit review.

Your pull request contains formal errors. Comments have been assigned to each commit in your pull request - please review and adjust. Feel free to ask for help if you need it!

**Comment by NamelessCoder** [comment]
Ignore my stupid bot... he thinks everything is an error ;)

**Comment by NamelessCoder** [comment]
Replaced by a ReflectionMethod-based implementation to avoid copying and maintaining code - see https://github.com/FluidTYPO3/flux/commit/62724fea18fb34cf2a2fee7e73ecd37c6075fd2e

Thanks for bringing this up!

**Comment by netzloesungen** [comment]
Thanks for solving this issue!

**Pull request closed without merging**
