### PR TITLE
[FEATURE] add radio field

### PR DESCRIPTION
**Pull request by boettner-it**
Hi Claus,

thought this one is missing but I am not absolutely sure if my change is ok and if it complies with your Git workflow. Treat this as a first request for a change.

Cheers
Robert.

### CODE REVIEW

**Comment by coding46** [comment]
Thanks for your contribution. It's really appreciated.

Would you mind doing some refactoring as with this solution there's lot of duplicated code with the flux:select element?
Maybe putting 'getItem' to AbstractMultiValueFormField and apply only the 'emptyOptions' stuff in Select. Same for other occurrences.

**Comment by boettner-it** [comment]
Hi @coding46,

np, just one question in advance. Would it be an option to let Select inherit from Radio to avoid duplication?

**Comment by NamelessCoder** [comment]
@boettner-it Yes, please subclass `Select` and `SelectViewHelper` for this! Internally in the core the radio rendering is a subset of select.

**Comment by NamelessCoder** [comment]
Manually subclassed to Select / SelectViewHelper and merged.

**Pull request closed without merging**
