### PR TITLE
[BUGFIX] Copy & Paste child elements

### PR DESCRIPTION
**Pull request by glucka**
Should solve #1632

### CODE REVIEW

**Comment by glucka** [comment]
I think this works only in Connected Mode.
I check it in Copy Mode tomorrow.

**Comment by glucka** [comment]
sorry i find  another bugs... i work on it

**Comment by NamelessCoder** [comment]
The last patch state looks like it was going in the right direction - though it might be best to split the patching up into two: one to solve the free-mode behavior and another to solve the copy-mode. It's currently a little difficult to tell which changes aim to solve which behavior.

PS: I think perhaps the bug you encountered last happened because this line was changed: https://github.com/FluidTYPO3/flux/pull/1659/files#diff-93ddaa2e34830c84cb681ad5c240d4b1L42 - there's a super-important difference in how colPos values are handled: only when a record is in "copy" mode should we re-calculate the colPos like this. In "connected" mode the colPos value is the same as the original language parent's colPos, in "free" mode it's relative to the translated parent. This code *probably* should still not be executed in connected mode ;)

**Comment by glucka** [comment]
Thanks for your hints Claus! You are right. 
Unfortunately i think cascading the copy cmdmap is not the right way. We should always use the $reference->copyMappingArray.
I continue to work on it!

**Pull request closed without merging**
