### PR TITLE
[BUGFIX] Copy & Paste child elements

### PR DESCRIPTION
**Pull request by glucka**
Should solve #1632

### CODE REVIEW

**Comment by rupasix** [comment]
**I don't have languages** on my current t3 v9 instance but still had issues with copying content between pages so i gave your PR a try. I've tested your PR using non admin user, and **everything from list below was working fine and predictible**:

- Copying nested (2 lvls) content with FAL inside same page,
- Copying nested (2 lvls) content with FAL to another existing page,
- Deleting nested (2 lvls),
- Copying nested (5 lvls) content with FAL inside same page,
- Copying nested (5 lvls) content with FAL to another existing page,
- Deleting nested (5 lvls),
- Creating copy of page with nested content (2lvl + 5lvl, FAL included in few ce),
- Deleting copied page with nested content (2lvl + 5lvl, FAL included in few ce),
- Clearing Recycler

**Comment by BenjaminBeck** [comment]
I applied this to a TYPO3 9.5.4-dev with two languages and tested:
- Translate (linked) content with nested grid and FAL-link (default -> 2nd language)
- Translate (copy) content with nested grid and FAL-link (default -> 2nd language)
- Copy page with nested grids and translation
- Copy grid with content into grid on other page (with translation)
- Copy grid with content into fluidpages column on other page (with translation)

I did not notice any error, great work - thx!

**Comment by glucka** [comment]
Hi @NamelessCoder, do you need any additional info for this PR?

**Comment by NamelessCoder** [comment]
@glucka I haven't yet had time to test it - but today should be the day. In any case we need the unit tests to be fixed since they still contain an expectation of a call to the cascade method you removed, so if have time to fix that please have a look ;)

**Comment by glucka** [comment]
@NamelessCoder I'm still busy for approx 2 weeks, then I can look again

**Comment by mithri** [comment]
@glucka You saved my day. It`s all working as expected. Thank you very much!

**Comment by andreaswolf** [comment]
Works percetly for me for the case described in #1670.

**Comment by NamelessCoder** [comment]
Thank you all for confirming the patch and @glucka for making it. There are just two minor tasks before this can be merged:

1. Failing unit test expectation must be corrected (by removing it)
2. Code can be cleaned up a bit in terms of CGL and extracting a few variables to ease readability, such as extracting arguments for copyRecord() and updateDB() for the very similar method calls, then calling the methods in only one place after preparing arguments.

**Comment by glucka** [comment]
with pleasure @NamelessCoder ;) I hope that ok now. I you find any problem please correct it!

**Comment by NamelessCoder** [comment]
Manually picked and cleaned up in https://github.com/FluidTYPO3/flux/commit/72a7e3e52df8f01cd9120dd1ccc81c675281b9e2. Only minor adjustments made to behavior, e.g. always passing language UID to allow free-mode copy from one language to another and prevent problems if copying empty pages.

**Pull request closed without merging**
