### PR TITLE
[BUGFIX] Added check for input value (#1407)

### PR DESCRIPTION
**Pull request by sypets**
I tried to follow the excellent contribution guidelines best as possible (https://fluidtypo3.org/documentation/contributing/contribution-guide.html). composer install was successfull. However vendor/bin/make, vendor/bin/checkstyle and vendor/bin/runtests are missing. 

Ran phpunit manually, 100% pass.
phpcbf had a number of fixes on several files that I did not changed, so I abandoned that.

Hope this is a sufficient PR. If not I will do my best to improve it.

### CODE REVIEW

**Comment by sypets** [comment]
I closed the initial issue, but I still think the check for input value makes sense, unless of course the entire function can be dropped for TYPO3 8.

**Comment by NamelessCoder** [comment]
My apologies for the outdated information in the contribution guide, it really needs an update. At this point all we require is that you do `composer install` and run `./vendor/bin/phpunit` - or simply wait for Travis to do the testing.

Good job on the patch and not least the issue description in #1407, detailed reproduction steps are *greatly* appreciated. And welcome to the list of contributors! :)

**Comment by sypets** [comment]
Ok. Thank you. I will try to work on a reproducible test case, if possible. Should we bother at all with TYPO3 7.6? Or only report problems (if any) on TYPO3 8?

**Comment by NamelessCoder** [comment]
> Should we bother at all with TYPO3 7.6? Or only report problems (if any) on TYPO3 8?

Let's start with TYPO3 8. When Flux 9.0 gets released the `legacy` branch will be updated to use `8.2.1` as starting point and becomes the recommended "version" to use on TYPO3 7.6. We can then backport a patch to `legacy` so people with TYPO3 7.6 can get the fix as well.

**Pull request merged**
