### PR TITLE
[FOLLOWUP][BUGFIX] Fix design for collapsing columns (#1297)

### PR DESCRIPTION
**Pull request by monosize**
The toggler was saved in the cache, after reoload the page layout, the state was wrong.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Looks like it's my fault this happened. The reason is I wanted to avoid (re-)processing Providers on every element - that's why the icon cache exists after all. If we do this second round of processing, the benefit of the cache is almost completely lost.

Is there another way we could handle this, e.g. adding the expanded/collapsed state to the cache identifier so toggling the state rebuilds / uses other entry?

**Comment by monosize** [comment]
I will think about this.

**Comment by monosize** [comment]
Here the new solution.

**Comment by NamelessCoder** [comment]
I took care of it meanwhile, in https://github.com/FluidTYPO3/flux/commit/9eca81187dae361e89eb78db3724d1e997a57de0 - didn't mean to hijack, but thought I'd better clean up my own mistake ;)

Solution causes a few additional method calls for each record but solves the problem with the wrong icon being retrieved.

**Comment by NamelessCoder** [comment]
Thank you so much for all the time you spend on Flux contributions, Frank! If you want to officially join the team just say the word ;)

**Comment by monosize** [comment]
@NamelessCoder That would be great to join the officially team! Yes I want ;-)

**Comment by NamelessCoder** [comment]
Welcome to the team Frank :) you should now have access to manage issues, merge/close pull requests and perform edits in pull requests that are not your own, for all our repositories. You already know nearly all of our work flow but if you've got questions, email me or catch me on IRC and I'll help you out.

If in doubt about anything don't hesitate to ask ;)

**Comment by cedricziel** [comment]
Welcome to the team and thank you for the contributions!

**Pull request closed without merging**
