### PR TITLE
Two minor fixes

### PR DESCRIPTION
**Pull request by jmverges**
I found two problems, the first one crashed FE and the second one Web->Page (BE)

### CODE REVIEW

**Comment by NamelessCoder** [comment]
#### This is an automated comment based on an automated formal commit review.

Your pull request contains formal errors. Comments have been assigned to each commit in your pull request - please review and adjust. Feel free to ask for help if you need it!

**Comment by NamelessCoder** [comment]
#### This is an automated comment based on an automated formal commit review.

Your pull request contains formal errors. Comments have been assigned to each commit in your pull request - please review and adjust. Feel free to ask for help if you need it!

**Comment by NamelessCoder** [comment]
#### This is an automated comment based on an automated formal commit review.

Your pull request contains formal errors. Comments have been assigned to each commit in your pull request - please review and adjust. Feel free to ask for help if you need it!

**Comment by NamelessCoder** [comment]
#### This is an automated comment based on an automated formal commit review.

Your pull request contains formal errors. Comments have been assigned to each commit in your pull request - please review and adjust. Feel free to ask for help if you need it!

**Comment by cedricziel** [comment]
Replaced by #767

**Pull request closed without merging**
