### PR TITLE
[FEATURE] show item footer as in regular drawItem function, i.e. fe_user...

### PR DESCRIPTION
**Pull request by netzloesungen**
Footer was only shown in elements with colPos not being 18181 but not in elements inside a flux:grid column

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Hi @netzloesungen - the pull request mentioned by @danilobuerger has now been merged. Would you mind rebasing this and implementing a similar solution in the new `PreviewView` class? Thanks!

**Comment by netzloesungen** [comment]
Hi @NamelessCoder!  I will try to implement this by the end of next week...

**Comment by danilobuerger** [comment]
Sorry for the extra work...

**Comment by netzloesungen** [comment]
well,... push -f is evil... closing this wasnt my intention. will be back...

**Comment by netzloesungen** [comment]
Sorry guys, i messed up the rebasing and had to create a new pull request then....

[FEATURE] show item footer #746

**Pull request closed without merging**
