### PR TITLE
Bugfixes for pasting elements with translations

### PR DESCRIPTION
**Pull request by BenjaminBeck**
Please do not merge - This is still work in progress.

Any comments, help or tips are welcome..

Related to #974

### CODE REVIEW

**Comment by NamelessCoder** [comment]
@BenjaminBeck Thanks for the pull request! Do you need advise/help about something specific or just the Q's you've noted in the source code? I'm happy to review but would like to make sure I cover all of it in the very first round.

**Comment by BenjaminBeck** [comment]
Hi @NamelessCoder 
i had mainly a lack of time and hoped to be able to use the functional tests ( #875 ).
I also found this bug in the typo3 bug tracker: https://forge.typo3.org/issues/60357 ( Pasting a localized content element into another colPos fails ). I want to have a look at that if this has something to do with this pasting problems. Give me a few more days - i´ll call for you when its ready to be reviewed.

**Comment by mkoehler2911** [comment]
Any updates here?

**Comment by BenjaminBeck** [comment]
I have to do a rebase on the current version and also test it with 7.6.
I´ll post & push any progress.

**Comment by robsonrobi** [comment]
@BenjaminBeck : Is there any progress? Localization with FLUX and TYPO3 7.6.4 makes still no fun. :-(

**Comment by robsonrobi** [comment]
We love FLUX BUT it is not possible to translate in friendly way. Nested FCEs localized the first time is okay, adding another FCE inside in the source language results in NO result, when hitting translate. Although all localized FCEs wich are on the root have the tx_flux_parent value of 767.

**Comment by deerfish** [comment]
Guten Tag
 
Vielen Dank für Ihre Nachricht.

Ich bin vom Donnerstag, 14. Juli 2016 bis und mit Montag, 18. Juli 2016 viel unterwegs, und nur sporadisch erreichbar.
 
Es kann daher zu Verzögerungen in meiner Reaktionszeit kommen. Ich bitte Sie entsprechen um etwas Geduld! In dringenden Fällen bin ich auf dem Mobile erreichbar.

Einen guten Tag wünscht

Damian Parpan



Damian Parpan
appline
Hirschengraben 52
6003 Luzern
Switzerland

T: +4141 266 0034
M: +4179 303 4878

Email: damian.parpan@appline.ch
www.appline.ch

**Comment by swissdude** [comment]
I know this is an old thread...
Are there any news on this issue?
Seems like translating nested elements is still broken in Flux 8.2.1.

**Comment by NamelessCoder** [comment]
Don't take this the wrong way because no offence is meant, but I'm tempted to quote the now dead single page site "any updates on this issue?" because as you can imagine, this is a question we get quite often and the answer is in 99% of cases the same (and we really would rather like to not hear about the 99% of cases to catch the last 1%). It gets asked so often someone somewhere actually decided to register a domain and put a single message on it.

It went a bit like this:

> No, there are no updates on this. All the communication about this issue is here, out in the open and available for all to see, and any progress that gets made *usually* (but not always) gets posted to the pull request or issue. This includes workarounds which our users are awesome enough to share with each other, and additional information that may help track down the cause of the issue.
>
> Contrary to businesses, the communication in open source communities is with few exceptions completely public. That's why if there are no updates on a certain issue, there _literally are no updates on that issue_.

Despite the slight sarcasm, the point is very clear: new comments which ask "any updates on this?" are not helpful and in nearly all cases yield no additional information - and they come at the cost of time for maintainers and subscribers who receive emails when comments arrive on pull requests or issues.

So not just on behalf of myself but also all other open source library maintainers:

Please don't ask us if there are updates to an issue. The answer is always "no, nothing you can't already read in public history".

Thanks in advance ;)

**Comment by BenjaminBeck** [comment]
I close this because it got too old and is not relevant anymore.

**Comment by NamelessCoder** [comment]
@BenjaminBeck we have a LOT of issues which will be solved by the pull request - you don't need to close them, I'll soon add the list of issue numbers to the pull request so they all get closed when it merges ;)

**Pull request closed without merging**
