### PR TITLE
[BUGFIX] Dbtable.* named form fields

### PR DESCRIPTION
**Pull request by glucka**
Save dbtable.* named flux form fields direct in db columns
Solve #1604

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Looks good!

**Comment by glucka** [comment]
Should/can i merge? :)

**Comment by NamelessCoder** [comment]
Please hang on, I'd like to run a test on this so we have two confirmations. If it works okay I'll merge ;)

Generally speaking we don't merge our own PRs, even when approved.

**Comment by glucka** [comment]
Ok, understood ;)

**Comment by NamelessCoder** [comment]
I this case it's because you created the commit on the `development` branch which means you can't create additional PRs - doing that will include the old commits and detect the new PR as a replacement.

The way to avoid this is to always create a branch starting from `development`, for example `feature/my-special-fix` and have one such branch for each PR.

If you run into the situation later on that you need to do work which depends on a PR that isn't merged, feel free to ping me for more git-methods. But until you're more comfortable with one-branch-per-PR I would recommend keeping the changes small and separate, and avoid making changes depend on each other.

**Pull request closed without merging**
