### PR TITLE
Fix extensionName override support

### PR DESCRIPTION
**Pull request by pkerling**
Follow-up for #809 

Tests run now, but $root->getExtensionName() is now completely gone. Is this a problem?

### CODE REVIEW

**Comment by NamelessCoder** [comment]
> $root->getExtensionName() is now completely gone. Is this a problem?

Yes, that would cause forms constructed using PHP objects to no longer be able to inherit the extension name from the root element - but perhaps an easy way to solve that and maybe also avoid the entire ViewHelperVariableContainer situation:

https://github.com/FluidTYPO3/flux/blob/development/Classes/Form/AbstractFormComponent.php#L158

If an additional line here was would always copy `$this->extensionName` to the created component, and then the AbstractFormViewHelper used `$container` rather than `$form` to create new components, then this should actually cause the right behavior in all contexts. This is, if I am remembering everything around this code correctly!

**Comment by NamelessCoder** [comment]
By the way, great stuff - thanks a lot for taking care of all these!

**Comment by pkerling** [comment]
AbstractFormViewHelper does not use createComponent at all, components are created by the subclasses (ex: AbstractFieldViewHelper::getPreparedComponent, SheetViewHelper::render). From the looks of it they all use `$this->getForm()->create[...]`. Additionally, they also propagate the extension name themselves `$sheet->setExtensionName($this->getExtensionName())`. Now inserting the code you mentioned into `createComponent` should solve the problem with PHP-created forms and the `$root->getExtensionName()` call being deleted. For ViewHelper-created forms, I see two possibilities:
* Go through every view helper creating form components and make sure they use `$this->getContainer()->create[...]` instead and call `setExtensionName` themselves _only_ if it is explicitly set by some source (e.g. `extensionName` argument). Also, make sure the root component always gets the extension name from the ControllerContext as fallback.
* Just leave it as it is and use the ViewHelperVariableContainer

**Comment by NamelessCoder** [comment]
Ach, right... the ViewHelpers do have a tendency to override the render method and don't share a "prepareComponent" method, at least not on the base class.

I'll vote for the solution that combines the PHP usage safeguard against removed $root combined with use of ViewHelperVariableContainer as suggested! Solves both problems with a minimum of changes in ViewHelpers' code.

**Comment by pkerling** [comment]
Should I see if I can do something about the failed coverage check?

**Comment by NamelessCoder** [comment]
You don't have to worry about those 0.02% - when we reach 99% I'll add new test cases.

**Comment by NamelessCoder** [comment]
...but we do still need the `createComponent` setting of parent name to be implemented since getting rid of root as source of extension name!

**Comment by pkerling** [comment]
Now I'm confused. Thought I addressed that in 8cc5c36, did I miss anything?

**Pull request merged**
