### PR TITLE
[BUGFIX] Correctly copy and move records in workspaces

### PR DESCRIPTION
**Pull request by NamelessCoder**
Fixes issues with copying and moving records in a
workspace, and rendering nested content in pages
that were moved in a workspace.

Close: #1724

### CODE REVIEW

**Comment by NamelessCoder** [comment]
@cweiske would you mind giving this PR a try before I merge? It solves both copy and move operations in workspace.

I've confirmed operation on TYPO3 v10.2 and I'm fairly sure the paste commands are identical on 9.5 LTS.

**Comment by NamelessCoder** [comment]
@cweiske Is the target page a workspace version / placeholder, and is the parent content element a workspace version / placeholder?

**Comment by cweiske** [comment]
I created all pages and elements freshly in the workspace.

**Comment by NamelessCoder** [comment]
Thanks - that looks the case I missed in the last test; when origin page is a placeholder. Will look into this!

**Comment by cweiske** [comment]
No, I still have the same problem that the child element is not copied.

**Comment by NamelessCoder** [comment]
Tested with TYPO3v10.2

* Copy from workspace version of page and content to new workspace version of page
* Copy from published page with workspace version of content to workspace version of page
* Copy from published page and content to workspace version of page
* Copy from published page and content to published page
* Copy published page in temp workspace (recurses to children of content)
* Copy published page in live workspace (recurses to children of content)

All should be working now, *if* the DataHandler command maps are the same on TYPO3v9 as on v10.2.

**Comment by cweiske** [comment]
Ok, copying a container with children in the workspace works now.
It also works when copying a container with children in live.

There is a thing I do not know if it's a bug or not:
- Create container + child in live
- Switch to workspace, create a second child
- Switch back to live
- Copy container
- Paste container
- The pasted container has two children now, although live only had one.

**Comment by NamelessCoder** [comment]
This probably is due to the removed workspace condition. I'll try to reintroduce this constraint, but only allow it to select records from either LIVE workspace and whichever workspace is currently active (sql `IN (0, $workspace)`). This should result in only being able to copy records that are published or belong to the active workspace (in your use case, the final copy should then have only one child record).

**Comment by NamelessCoder** [comment]
Thanks Christian! Merge time :)

**Pull request merged**
