### PR TITLE
[BUGFIX] Paste into icon is shown twice in TYPO3v8.6

### PR DESCRIPTION
**Pull request by monosize**
since v8.6 the paste icons are inserted with javascript.

change the icon from "actions-document-paste-after" into "actions-document-paste-into" for TYPO3 version lower than 8.6

### CODE REVIEW

**Comment by monosize** [comment]
@NamelessCoder Hi Claus, we should insert the 'paste as reference' button in TYPO3v8.6+ also with javascript if #1305 is solved. So the button would shown on non flux:grid columns ;-)

**Comment by NamelessCoder** [comment]
Hi Frank - I think we should use the CompatibilityRegistry for this one (define in localconf) and register for example a boolean variable named `PreviewViev::class . '->drawPasteIcon' that we set to `true` for `7.6.0` and change to `false` on `8.6.0` and above. Then simply read that variable directly in a condition in PreviewView so the icon is only written if the variable is true.

And yes to drawing our paste icons with JS to also render paste as reference in non-flux columns! :)

**Comment by monosize** [comment]
Hi Claus, now it uses CompatibilityRegistry.

**Comment by monosize** [comment]
@NamelessCoder Cut and Paste in empty flux:grid column doesn't work see https://github.com/FluidTYPO3/flux/pull/1362/commits/d8b5490737dbe1e64747ba8663de4f55e25a89bd#diff-1643673e7b3b4c4d282987bd9ccfd3b4R244 from my PR

**Comment by monosize** [comment]
@NamelessCoder The problem is to insert the element at the beginning of the column ( with or without elements in the flux:grid column). Cut an element with the context menu and then click on the paste icon to insert it at the top of a flux:grid column.

**Comment by monosize** [comment]
Bugfix is here #1363

**Pull request merged**
