### PR TITLE
[FEATURE] Add PHP 7.2 travis builds

### PR DESCRIPTION
**Pull request by Lagerregal**

### CODE REVIEW

**Comment by Lagerregal** [comment]
see #1487

**Comment by cedricziel** [comment]
No closing needed - we should keep your build and allow failures on it.

**Comment by cedricziel** [comment]
```
matrix:
  # ...
  allow_failures:
  - php: "7.2"
    env: COVERAGE="NO" TYPO3_VERSION="dev-master"
```

Should do the trick. I cannot amend your commit, since you disabled edits for maintainers.

**Comment by NamelessCoder** [comment]
Applied this one myself after doing the Object -> SectionObject rename. Thanks again, @Lagerregal, for opening the ball :)

**Pull request closed without merging**
