### PR TITLE
[TASK] Make all ViewHelpers compilable

### PR DESCRIPTION
**Pull request by NamelessCoder**

### CODE REVIEW

**Comment by mneuhaus** [comment]
fixed a bug in the [compilable method of the Widget/GridViewHelper](https://github.com/FluidTYPO3/flux/commit/e77915133e23aa169202673489816bbf58c62774#commitcomment-13654733), aside from that +1 from me

**Comment by xf-** [comment]
v6 and v7 or only v7?

**Comment by NamelessCoder** [comment]
> v6 and v7 or only v7?

Shouldn't matter, compiling hasn't been changed :)

**Comment by NamelessCoder** [comment]
Thanks Marc - if you're happy with this I'd say good to merge.

**Pull request merged**
